### ISSUE TITLE
Casting numbers above Number.MAX_VALUE fail

### ISSUE THREAD

**Issue by kamui** [nire0510/qs#2]
I have a query string that looks like `?order_number=77272977463618461251`. `QS().get("order_number")` casts this to `77272977463618450000`. I believe you should probably see if the value is above `Number.MAX_VALUE` or verify that the casted value is the same as the original value somehow.

**Comment by nire0510** [comment]
Great catch, @kamui , **thanks!**
Fixed on version 0.3.10.
